name: 'lupdate-action'
description: 'Update translation sources'
author: 'plfiorini'

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  sources_path:
    description: 'Path to sources.json'
    default: '.tx/sources.json'
    required: true
